### ISSUE TITLE
Optional Pod Labels in Helm Chart

### ISSUE THREAD

**Issue by muyisbox** [clemlesne/blue-agent#131]
The Helm Chart Presently as the option to add additional pod annotations, however additional pod labels would be useful to enable workload id to access other Azure Resources.

Also the ability to add extra sidecar containers could be useful

**Comment by clemlesne** [comment]
Hello @muyisbox,

> The Helm Chart Presently as the option to add additional pod annotations, however additional pod labels would be useful to enable workload id to access other Azure Resources

The Helm chart has the `annotations` configuration, allowing to configure the Pod Annotations (in `spec.template.metadata.annotations`).

Is it solving your need?

> Also the ability to add extra sidecar containers could be useful

Version `6.6.0` is out with this feature (commit b439cd8ff3f96b225dd0deb8defefeef6747b1d1)! A field `sidecarContainers` is now available in Helm. Can you test? :)

**Comment by clemlesne** [comment]
I'm clothing this issue as there is no update. Don't hesitate to reopen and comment.
