### ISSUE TITLE
[Bug]: openssl command not found

### ISSUE THREAD

**Issue by ckmurrer** [clemlesne/blue-agent#247]
I am attempting to install the agent on a Kubernetes cluster in an offline environment. I had obtained my DevOps SSL certificate and entered in the configMap like the documentation suggests in the advanced section of the docs. However, when running a helm install it prints:
"Adding custom SSL certificates"
"Searching for *.crt in /app-root/azp-custom-certs"
finds my one cert then errors with
"start.sh: line 91: openssl: command not found"

**Comment by clemlesne** [comment]
If I understand well, OpenSSL executable is not resolved/installed on the container. This seems 100% a bug.

Can you give the flavor you’re using and its version/hash?

**Comment by ckmurrer** [comment]
I was on a RHEL8 machine using ubi8-7.0.0 and the hash should be index digest sha256: fd2d3dd2224200490866339b9c207b59f7d0cc5102315c7099e68191e566f427 
I also tried using ubi8-latest around the same time as the ubi8-7.0.0 but I have since deleted that image and no longer have the hash for it apologies.

**Comment by clemlesne** [comment]
Related: https://repo1.dso.mil/dsop/redhat/ubi/8.x/ubi8/-/issues/34

**Comment by clemlesne** [comment]
Fixed with 4a44d2cac0b041895aadcc8afa1c1d2e3a7e168b.

Will be on the `v7.0.1`!

**Comment by clemlesne** [comment]
v7.0.3 is out, is includes the correction.

**Comment by clemlesne** [comment]
Please reopen if it shows again! I'll invest time to add that in test cases (will be time consuming).
