### ISSUE TITLE
Error: INSTALLATION FAILED

### ISSUE THREAD

**Issue by jepeto007** [clemlesne/blue-agent#279]
Hello, I receive this erreor when try a helm install on version 7 :

Error: INSTALLATION FAILED: Deployment.apps "blue-agent711" is invalid: spec.template.spec.containers[0].lifecycle.preStop.exec.command: Required value

**Comment by clemlesne** [comment]
Can you share your helm values config and the generated deployment resource?

**Comment by clemlesne** [comment]
Maybe related to #242.

**Comment by clemlesne** [comment]
Can you please re-test with version `v7.1.2`? The issue might be fixed already.

**Comment by jepeto007** [comment]
Yes, it's fixed. Thanks!

Le dim. 29 sept. 2024, 05 h 37, Clémence Lesné ***@***.***> a
écrit :
