### ISSUE TITLE
[Feature]: Adding feature to agent dockerfile

### ISSUE THREAD

**Issue by piotrlaczykowski** [clemlesne/blue-agent#285]
### Feature

We just switched to newer kubernetes and lost the option to build in agents using host docker.sock :/

It would be nice to have a second pipeline to build your docker images in azure pipelines.
I need some modification like:
Build in helm
Build in kubectl
Build in node
Is it possible to use docker instead of buildKit?

### Use case

I won't install it in every run.

### Alternatives

I consider rewriting your pipeline to azure pipelines by my self

**Comment by clemlesne** [comment]
Indeed Docker socket is deprecated since `1.20`.

Normally, BuildKit should work with RootlessKit (https://clemlesne.github.io/blue-agent/docs/advanced-topics/docker-in-docker/#how-to-use-the-bundled-buildkit). Did you tried that?

**Comment by piotrlaczykowski** [comment]
> Indeed Docker socket is deprecated since Kubernetes `1.20`.
> 
> Normally, BuildKit should work with RootlessKit and QEMU (https://clemlesne.github.io/blue-agent/docs/advanced-topics/docker-in-docker/#how-to-use-the-bundled-buildkit). Did you tried that?

Oh so the combo of the BuildKit RootlessKit and QEMU will allow to use docker build, run etc?

**Comment by clemlesne** [comment]
Yes it should, like described in the doc :) But I have no integration tests yet to test that feature I implemented last year, I’m not 100% sure it’s working.

Btw for better performances (QEMU can be atrociously slow), you can use Azure Container Registries (https://learn.microsoft.com/en-us/azure/container-registry/container-registry-tasks-overview).

**Comment by clemlesne** [comment]
I close that issue for now, don’t hesitate one sec if you have any questions/issues!

**Comment by clemlesne** [comment]
So, it uses docker cli in the backend?
