### ISSUE TITLE
[Bug]: Keda doesn't scale down agent when queue is empty

### ISSUE THREAD

**Issue by Bastichou** [clemlesne/blue-agent#298]
### Problem

For some reasons, Keda is scaling more agent than the queued jobs in Azure pipeline.

I'm suspecting a race condition between the startup time of the agent and the pollingInterval of ScaledJob. The time the agent is being scheduled by K8s and consume the queue, Keda would start another agent if it reach the pollingInterval and there is still jobs in the queue. 

Not sure Keda means to solve this situation but maybe we could we setup a idle time in the agent to automatically unregister and stop after 3m of idle time ?

### Impact

A few agents can remain in the Kubernetes cluster until a new ci job is scheduled by Azure Pipeline. It will never get removed until a new job is executed.

### Deployment

AKS

### Version

9.0.0

**Comment by clemlesne** [comment]
If I understand well, when a job is triggered on Azure DevOps, you see multiple instances starting.

Questions:

- How much time an instance take to start on your cluster (from pod object creation to registered in Azure DevOps)?
- Do you see this every time? If not, do you see a pattern?

**Comment by clemlesne** [comment]
The feature is now stabilized in `develop` branch. Will be merged in the next version.

Feedback appreciated!
