### ISSUE TITLE
Unable to resolve Root TLS Certificate out of the box

### ISSUE THREAD

**Issue by biggiethehacker** [clemlesne/blue-agent#307]
I am trying to add a few additional software (helm, kubernetes etc.) to the blue-agent docker image but I am unable to do so because the download command is unable to verify the local issuer certificate. This also happen with any curl based downloads. Any idea how to fix this?

Example Dockerfile: 
```
FROM docker.io/clemlesne/blue-agent:bookworm-7.1.2

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    apt-get clean

RUN az aks install-cli
```

Example Error:
```
#6 [3/3] RUN az aks install-cli
#6 25.23 WARNING: The detected architecture of current device is "x86_64", and the binary for "amd64" will be downloaded. If the detection is wrong, please download and install the binary corresponding to the appropriate architecture.
#6 25.23 WARNING: No version specified, will get the latest version of kubectl from "https://storage.googleapis.com/kubernetes-release/release/stable.txt"
#6 26.67 ERROR: The command failed with an unexpected error. Here is the traceback:
#6 26.81 ERROR: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>
....
```

**Comment by clemlesne** [comment]
It seems the root TLS certificates are not resolved out of the box. This is not normal and should be solved.

I see you are using the `v7.2.1`. Can you try using the `v9.0.0`? One of the features added is the upgrade of Python to Python 3.11 on all images.

Is the issue persist, can you try installing `certifi` package with `python3 -m pip install --upgrade certifi`?

**Comment by biggiethehacker** [comment]
Issue persists when using `REQUEST_CA_BUNDLE` and `SSL_CERT_FILE` on the `v7.1.2` image. 

Dockerfile - 
```
FROM docker.io/clemlesne/blue-agent:bookworm-7.1.2

ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

# Update Certs
RUN apt-get update && \
    apt-get install -y ca-certificates && \
    apt-get clean

RUN curl -fsSL -o ./helm-v3.14.2-linux-amd64.tar.gz https://get.helm.sh/helm-v3.14.2-linux-amd64.tar.gz 
```

Error - 
```
 > [3/3] RUN curl -fsSL -o ./helm-v3.14.2-linux-amd64.tar.gz https://get.helm.sh/helm-v3.14.2-linux-amd64.tar.gz:
1.919 curl: (60) SSL certificate problem: unable to get local issuer certificate
1.919 More details here: https://curl.se/docs/sslcerts.html
```

For `v9.0.0` issue exists out of the box as well as with the env variables when trying to run `curl -fsSL -o ./helm-v3.14.2-linux-amd64.tar.gz https://get.helm.sh/helm-v3.14.2-linux-amd64.tar.gz ` or `az aks install-cli`.

Temporarily, here is what I have been doing as a workaround, but this will only work if using `curl` directly- 

Dockerfile - 
```
FROM docker.io/clemlesne/blue-agent:bookworm-9.0.0

RUN openssl s_client -showcerts -servername get.helm.sh -connect get.helm.sh:443 > /etc/ssl/certs/cacert.pem \
    && curl --cacert /etc/ssl/certs/cacert.pem -fsSL -o ./helm-v3.14.2-linux-amd64.tar.gz https://get.helm.sh/helm-v3.14.2-linux-amd64.tar.gz
```

**Comment by clemlesne** [comment]
Just tested. On my laptop, build is working out of the work both with `v7.2.1` and `v9.0.0`.

It seems your computer anti-virus is placeed in a man in the middle with a custom forged certificate, which is abviously not included in the standard container.

Can you investigate on that side?

**Comment by biggiethehacker** [comment]
If it's working on your machine, then it is likely something to do with my anti-virus (this is after all my company's machine and they do go overboard with their setup). I will close this issue out. Thank you for your help!

**Comment by clemlesne** [comment]
Don't worry. Don't hesitate to reopen if needed.
